### ISSUE TITLE
Optimize randomisation

### ISSUE THREAD

**Issue by micheldejoode** [spiffytech/random_bibleizer#2]
I really like your idea of choosing a random bible chapter. I'm using your idea on a website, but found out the randomisation is not optimal because the code first chooses a random bible book, and then a random chapter. Because some books are longer and other books shorter not all chapters are picked even. I've made a testpage which shows this problem. The solution is to create an index of all books/chapters (1189) and random pick a number of this index. In an other test page with this index you can see all chapters are picked even. Maybe you can add this fix to your randomisation engine.

**Comment by spiffytech** [comment]
Hi! Thanks for the feedback. I've gotten this request from a couple of people, but have declined to make the change in the past as philosophically I'd prefer to sample the Bible evenly by book, rather than giving Psalms the same weight as the Minor Prophets and the Pauline Epistles combined.

However, I'm probably going to circle around to this codebase again in the near future, and at that time I'll add an option to do precisely what you requested.

**Comment by micheldejoode** [comment]
Thanks for your reply! Yes, there are good arguments for both ways. Both ways are interesting to explore the Bible! Good luck with everything. Greetings, Michel

Outlook voor Android downloaden<https://aka.ms/ghei36>

________________________________

**Comment by micheldejoode** [comment]
By the way, here is my version, based on your code, it's in Dutch language: https://micheldejoode.github.io/WillekeurigBijbelHoofdstuk/

Outlook voor Android downloaden<https://aka.ms/ghei36>

________________________________

**Comment by spiffytech** [comment]
Very nice!

I spent the evening and morning doing a rewrite with modern libraries, which includes an option for choosing the randomization engine. It also includes the oft-requested feature of remembering the translation you last used.

**Comment by micheldejoode** [comment]
Great man, thanks! I will look at the code soon.

Outlook voor Android downloaden<https://aka.ms/ghei36>

________________________________
