### ISSUE TITLE
Progressive Web App?

### ISSUE THREAD

**Issue by benkaiser** [spiffytech/random_bibleizer#4]
Hey @spiffytech, what are your thoughts on adding a web app manifest so users can 'install' on their device with an icon and all?

Could help it feel like a self-contained experience rather than just a website entrypoint.

**Comment by spiffytech** [comment]
That's a good idea. I give much thought to PWA for the Bibleizer, since in my mind the cool parts of PWA are offline support or Web Share Target, which don't make sense for a glorified iframe wrapper.

But enough people come to the Bibleizer (23k sessions each month), I'll bet someone would like to have it on their home screen.

I've pushed a webmanifest and favicons. Thanks for the suggestion!

**Comment by benkaiser** [comment]
Wow that was insanely fast! Thanks a bunch!

That's awesome to hear it's getting so much usage.
